- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: List Pods in namespace
      k8s_info:
        kind: Pod
        namespace: kube-system
      register: kube_system_pods_list
    - name: Show the list of pods
      debug:
        msg: "{{ item | json_query('metadata.name') }}"
      loop: '{{kube_system_pods_list.resources}}'
      loop_control:
        label: "Pod(Namespace: {{item | json_query('metadata.namespace') }})"
