- hosts: localhost
  connection: local
  collections:
    - community.kubernetes
  tasks:
    - name: create empty file
      file:
        path: "/home/test_file.txt"
        state: touch
      become: yes
